# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 751)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 911, 751))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../img/white.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, -10, 231, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../img/logoLfNutri.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 200, 621, 361))
        self.label_3.setStyleSheet("\n"
"background-color:transparent;\n"
"border-radius: 18px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../img/cadastro.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 220, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 320, 171, 21))
        self.lineEdit.setStyleSheet("border-radius: 10px;\n"
"color: rgb(120, 120, 120);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 370, 171, 21))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;\n"
"color: rgb(120, 120, 120);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.entrarBtn = QtWidgets.QPushButton(self.centralwidget)
        self.entrarBtn.setGeometry(QtCore.QRect(250, 420, 75, 23))
        self.entrarBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: white;\n"
"")
        self.entrarBtn.setObjectName("entrarBtn")
        self.cadastrarBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cadastrarBtn.setGeometry(QtCore.QRect(540, 390, 101, 61))
        self.cadastrarBtn.setStyleSheet("border-radius: 10px;\n"
"background-color: white;\n"
"")
        self.cadastrarBtn.setObjectName("cadastrarBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Login"))
        self.label_5.setText(_translate("MainWindow", "Cadastro"))
        self.lineEdit.setText(_translate("MainWindow", "   Usuário"))
        self.lineEdit_2.setText(_translate("MainWindow", "   Senha"))
        self.entrarBtn.setText(_translate("MainWindow", "Entrar"))
        self.cadastrarBtn.setText(_translate("MainWindow", "Cadastrar"))
